### ISSUE TITLE
multiple default providers

### ISSUE THREAD

**Issue by JDHatman** [glarizza/puppet-property_list_key#15]
Hello.  Thank you for all of your work. I'm having a problem on operating system prior to Mavericks.  

Here is the code i'm enforcing in my manifest:

property_list_key { 'AdditionalHttpHeaders':
  ensure     => present,
  path       => '/Library/Preferences/ManagedInstalls.plist',
  key        => 'AdditionalHttpHeaders',
  value      => [ 'Authorization: Basic XXXXXXXXXXXXXXXX' ],
  value_type => array,
  provider   => cfpropertylist,
}

On Mavericks, all works as expected.  On 10.6-10.8 it still works however there is a warning given.

munkitest1ml:~ jhatm0$ sudo puppet agent --test
Password:
Info: Retrieving plugin
Info: Loading facts in /var/lib/puppet/lib/facter/app_inventory.rb
Info: Loading facts in /var/lib/puppet/lib/facter/concat_basedir.rb
Info: Loading facts in /var/lib/puppet/lib/facter/facter_dot_d.rb
Info: Loading facts in /var/lib/puppet/lib/facter/has_x11.rb
Info: Loading facts in /var/lib/puppet/lib/facter/ip6tables_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/iptables_persistent_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/iptables_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mac_battery_charge_percent.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mac_battery_charging.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mac_battery_cycles.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mac_battery_health.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mac_current_user.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mac_encryption_enabled.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mac_flash_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mac_has_wireless.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mac_java_vendor.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mac_java_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mac_laptop.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mac_memory_in_gb.rb
Info: Loading facts in /var/lib/puppet/lib/facter/mac_timezone.rb
Info: Loading facts in /var/lib/puppet/lib/facter/munki_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/os_maj_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/pe_version.rb
Info: Loading facts in /var/lib/puppet/lib/facter/primary_user.rb
Info: Loading facts in /var/lib/puppet/lib/facter/printers.rb
Info: Loading facts in /var/lib/puppet/lib/facter/profiles.rb
Info: Loading facts in /var/lib/puppet/lib/facter/puppet_vardir.rb
Info: Loading facts in /var/lib/puppet/lib/facter/rabbitmq_erlang_cookie.rb
Info: Loading facts in /var/lib/puppet/lib/facter/root_home.rb
Info: Caching catalog for munkitest1ml.local
Warning: Found multiple default providers for property_list_key: cfpropertylist, rubycocoa; using cfpropertylist
Info: Applying configuration version '1395416415'
Notice: Finished catalog run in 58.26 seconds

Why are the older operating systems not using cfpropertylist when I have specified it in the manifest?

**Comment by JDHatman** [comment]
I should mention as well that sometime the warning is listed in the reverse order.

Warning: Found multiple default providers for property_list_key: rubycocoa, cfpropertylist; using rubycocoa

**Comment by glarizza** [comment]
Glad to see you got it working (and, again, sorry for taking for-damn-ever to write up a full email).  The reason you're seeing this is because each provider is defaulting itself according to the "feature" present (and, by feature, I mean what Ruby library is present...so either Rubycocoa or CFPropertylist).  See https://github.com/glarizza/puppet-property_list_key/blob/master/lib/puppet/provider/property_list_key/cfpropertylist.rb#L5 and https://github.com/glarizza/puppet-property_list_key/blob/master/lib/puppet/provider/property_list_key/rubycocoa.rb#L6) and you're running on machines that have BOTH Rubycocoa AND CFPropertylist (i.e. 10.6 - 10.8 machines).  Mavericks lacks Rubycocoa, so there's only one choice.  Puppet doesn't do well with two 'defaults', and thus warns you.  It also decides to use its 'best judgement' to pick one...but that's somewhat random too.

The solution to this will be for me to most likely just pick one as a default (probably cfpropertylist) and remove the default from the other (and require people to explicitly need to choose 'rubycocoa' if they want/need it).  Let me see if I can get that updated and pushed here soon

**Comment by JDHatman** [comment]
Thanks. I appreciate it!—

**Comment by JDHatman** [comment]
Were you able to make any progress on this?

**Comment by glarizza** [comment]
Should be resolved by this --> https://github.com/glarizza/puppet-property_list_key/pull/16

**Comment by JDHatman** [comment]
Works perfectly. Thanks!

Sent from Mailbox for iPhone
—
Jason Hatman
270-790-1139
